### ISSUE TITLE
Selenium AttributeError

### ISSUE THREAD

**Issue by sanskarfc** [praveenVnktsh/mitacs-project-extractor#4]
Selenium AttributeError: ‘WebDriver’ object has no attribute ‘find_element_by_xpath’, 'find_element_by_id'.

Starting from version 4.3.0., selenium has changed the usual API driver.find_element_by_xxx. Instead, the new method syntax is now simply driver.find_element(by_what, element).

**Comment by praveenVnktsh** [comment]
Can u submit a PR please?

**Comment by LSBispo** [comment]
Hi, ur using Python ?
